import type { Nozzle } from './nozzleComparison.types';

/**
 * Conjunto de Teste Controlado e Isolado para Testes Unitários
 * Contém amostras de bicos de cone vazio, fenda padrão ISO, indução de ar e modulares (pastilha + difusor)
 */
export const TEST_NOZZLES: Nozzle[] = [
  {
    id: 'test_albuz_atr_amarelo',
    brand: 'Albuz',
    model: 'ATR',
    modelNorm: 'ATR-80 | Amarelo',
    isTop: true,
    nozzleType: 'Cone vazio',
    sprayFunction: 'Arboricultura/Viticultura',
    isIsoNozzle: false,
    isoCode: undefined,
    colorStandardType: 'Fabricante',
    driftHazardLevel: 'Alto',
    mainApplications: 'Fungicidas/Inseticidas',
    notes: 'Bico de cone vazio para tratamentos em copa.',
    sprayAngleDeg: 80,
    color: 'Amarelo',
    referencePressureBar: 10,
    nominalFlowLMin: 1.03,
    pressureMinBar: 5,
    pressureMaxBar: 25,
    recommendedFilterMesh: 50,
    dataType: 'oficial',
    confidenceLevel: 'alto',
    dropletClass5bar: 'F',
    dropletClass10bar: 'VF',
    dropletClass15bar: 'VF',
    sourceBody: 'Catálogo Albuz',
    sourceLink: 'Spray nozzles'
  },
  {
    id: 'test_teejet_xr_amarelo',
    brand: 'TeeJet',
    model: 'XR',
    modelNorm: 'XR-110 | 02-Amarelo',
    isTop: true,
    nozzleType: 'Fenda',
    sprayFunction: 'Culturas Baixas',
    isIsoNozzle: true,
    isoCode: '02',
    colorStandardType: 'ISO',
    driftHazardLevel: 'Alto',
    mainApplications: 'Fungicidas/Herbicidas',
    notes: 'Bico de fenda com amplo leque de pressões.',
    sprayAngleDeg: 110,
    color: 'Amarelo',
    referencePressureBar: 3,
    nominalFlowLMin: 0.79,
    pressureMinBar: 1,
    pressureMaxBar: 4,
    recommendedFilterMesh: 50,
    dataType: 'oficial',
    confidenceLevel: 'alto',
    dropletClass5bar: 'F',
    sourceBody: 'TeeJet Catalog 51A',
    sourceLink: 'teejet.com'
  },
  {
    id: 'test_lechler_idk_amarelo',
    brand: 'Lechler',
    model: 'IDK',
    modelNorm: 'IDK-120 | 02-Amarelo',
    isTop: true,
    nozzleType: 'Fenda com indução de ar',
    sprayFunction: 'Culturas Baixas / Herbicidas',
    isIsoNozzle: true,
    isoCode: '02',
    colorStandardType: 'ISO',
    driftHazardLevel: 'Baixo',
    mainApplications: 'Herbicidas/Fungicidas anti-deriva',
    notes: 'Bico de indução de ar com redução de deriva de 90%.',
    sprayAngleDeg: 120,
    color: 'Amarelo',
    referencePressureBar: 3,
    nominalFlowLMin: 0.79,
    pressureMinBar: 1.5,
    pressureMaxBar: 6,
    recommendedFilterMesh: 50,
    dataType: 'oficial',
    confidenceLevel: 'alto',
    dropletClass5bar: 'C',
    sourceBody: 'Catálogo Lechler',
    sourceLink: 'lechler.de'
  },
  {
    id: 'test_albuz_disc_core_ad1_ac13',
    brand: 'Albuz',
    model: 'Disc & Core',
    modelNorm: 'Disc & Core | AD 1 + AC 13',
    isTop: false,
    nozzleType: 'Cone vazio',
    sprayFunction: 'Arboricultura/Viticultura',
    isIsoNozzle: false,
    driftHazardLevel: 'Alto',
    mainApplications: 'Fungicidas/Inseticidas',
    notes: 'Combinação modular de pastilha e difusor.',
    sprayAngleDeg: '70-79',
    disc: 'AD 1',
    swirlPlate: 'AC 13',
    referencePressureBar: 10,
    nominalFlowLMin: 0.41,
    pressureMinBar: 3,
    pressureMaxBar: 20,
    dataType: 'oficial',
    confidenceLevel: 'alto',
    dropletClass5bar: 'F',
    dropletClass10bar: 'F',
    dropletClass15bar: 'F',
    sourceBody: 'Catálogo Albuz',
    sourceLink: 'Spray nozzles'
  }
];
